import { db } from "@/lib/db";
import { items } from "@/lib/schema";

const SEED_ITEMS = [
  { hindiName: "चावल सामान्य", name: "Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 60, purchasePrice: 50, stock: 0, minStock: 10, gst: 5 },
  { hindiName: "बासमती चावल", name: "Basmati Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 130, purchasePrice: 108, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "दुबराज चावल", name: "Dubraj Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 90, purchasePrice: 75, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सोना मसूरी चावल", name: "Sona Masoori Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 70, purchasePrice: 58, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मिनी केतकी चावल", name: "Mini Ketki Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 65, purchasePrice: 54, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "पोनी चावल", name: "Poni Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "उसना चावल", name: "Usna Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 52, purchasePrice: 43, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "इंद्रायणी चावल", name: "Indrayani Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 75, purchasePrice: 62, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "कोलम चावल", name: "Kolam Chawal", category: "अनाज/दालें", unit: "किलो", mrp: 58, purchasePrice: 48, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "आटा गेहूँ", name: "Gehun Aata", category: "अनाज/दालें", unit: "किलो", mrp: 45, purchasePrice: 37, stock: 0, minStock: 20, gst: 5 },
  { hindiName: "आटा मध्यम", name: "Gehun Aata Medium", category: "अनाज/दालें", unit: "किलो", mrp: 48, purchasePrice: 40, stock: 0, minStock: 10, gst: 5 },
  { hindiName: "आटा मैदा", name: "Maida", category: "अनाज/दालें", unit: "किलो", mrp: 40, purchasePrice: 33, stock: 0, minStock: 10, gst: 5 },
  { hindiName: "बेसन", name: "Besan", category: "अनाज/दालें", unit: "किलो", mrp: 80, purchasePrice: 66, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "बेसन मोटा", name: "Besan Mota", category: "अनाज/दालें", unit: "किलो", mrp: 75, purchasePrice: 62, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सूजी बारीक", name: "Suji Barik", category: "अनाज/दालें", unit: "किलो", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सूजी मोटी", name: "Suji Moti", category: "अनाज/दालें", unit: "किलो", mrp: 44, purchasePrice: 36, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "रवा", name: "Rava", category: "अनाज/दालें", unit: "किलो", mrp: 44, purchasePrice: 36, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मक्का आटा", name: "Makka Aata", category: "अनाज/दालें", unit: "किलो", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "ज्वार आटा", name: "Jowar Aata", category: "अनाज/दालें", unit: "किलो", mrp: 38, purchasePrice: 31, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "बाजरा आटा", name: "Bajra Aata", category: "अनाज/दालें", unit: "किलो", mrp: 36, purchasePrice: 29, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "रागी आटा", name: "Ragi Aata", category: "अनाज/दालें", unit: "किलो", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "जौ आटा", name: "Jau Aata", category: "अनाज/दालें", unit: "किलो", mrp: 42, purchasePrice: 34, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मल्टीग्रेन आटा", name: "Multigrain Aata", category: "अनाज/दालें", unit: "किलो", mrp: 60, purchasePrice: 50, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "अरहर दाल", name: "Arhar Dal", category: "अनाज/दालें", unit: "किलो", mrp: 140, purchasePrice: 116, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मूंग दाल", name: "Moong Dal", category: "अनाज/दालें", unit: "किलो", mrp: 120, purchasePrice: 99, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मसूर दाल", name: "Masoor Dal", category: "अनाज/दालें", unit: "किलो", mrp: 100, purchasePrice: 83, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चना दाल", name: "Chana Dal", category: "अनाज/दालें", unit: "किलो", mrp: 90, purchasePrice: 74, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "उड़द दाल", name: "Urad Dal", category: "अनाज/दालें", unit: "किलो", mrp: 130, purchasePrice: 107, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "उड़द दाल छिलका", name: "Urad Dal Chilka", category: "अनाज/दालें", unit: "किलो", mrp: 125, purchasePrice: 103, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मूंग दाल छिलका", name: "Moong Dal Chilka", category: "अनाज/दालें", unit: "किलो", mrp: 115, purchasePrice: 95, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "राजमा", name: "Rajma", category: "अनाज/दालें", unit: "किलो", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "राजमा लाल", name: "Rajma Lal", category: "अनाज/दालें", unit: "किलो", mrp: 160, purchasePrice: 132, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काबुली चना", name: "Kabuli Chana", category: "अनाज/दालें", unit: "किलो", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काला चना", name: "Kala Chana", category: "अनाज/दालें", unit: "किलो", mrp: 90, purchasePrice: 74, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "हरे मूंग साबुत", name: "Hare Moong Sabut", category: "अनाज/दालें", unit: "किलो", mrp: 110, purchasePrice: 91, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "लोबिया", name: "Lobia", category: "अनाज/दालें", unit: "किलो", mrp: 95, purchasePrice: 78, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मोठ", name: "Moth", category: "अनाज/दालें", unit: "किलो", mrp: 85, purchasePrice: 70, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "कुलथी", name: "Kulthi", category: "अनाज/दालें", unit: "किलो", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "पोहा बारीक", name: "Poha Barik", category: "अनाज/दालें", unit: "किलो", mrp: 52, purchasePrice: 43, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "पोहा मोटा", name: "Poha Mota", category: "अनाज/दालें", unit: "किलो", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "साबूदाना", name: "Sabudana", category: "अनाज/दालें", unit: "किलो", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "साबूदाना छोटा", name: "Sabudana Chota", category: "अनाज/दालें", unit: "किलो", mrp: 78, purchasePrice: 64, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मूंगफली दाना", name: "Moongphali Dana", category: "अनाज/दालें", unit: "किलो", mrp: 100, purchasePrice: 83, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "चिरवा", name: "Chirva", category: "अनाज/दालें", unit: "किलो", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मुरमुरा", name: "Murmura", category: "अनाज/दालें", unit: "किलो", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सरसों तेल 1ली", name: "Sarson Tel 1L", category: "तेल/घी", unit: "नग", mrp: 180, purchasePrice: 148, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सरसों तेल 2ली", name: "Sarson Tel 2L", category: "तेल/घी", unit: "नग", mrp: 350, purchasePrice: 288, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सरसों तेल 5ली", name: "Sarson Tel 5L", category: "तेल/घी", unit: "नग", mrp: 850, purchasePrice: 700, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सरसों तेल 15ली", name: "Sarson Tel 15L", category: "तेल/घी", unit: "नग", mrp: 2400, purchasePrice: 1980, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "रिफाइंड तेल 1ली", name: "Refined Tel 1L", category: "तेल/घी", unit: "नग", mrp: 160, purchasePrice: 132, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "रिफाइंड तेल 2ली", name: "Refined Tel 2L", category: "तेल/घी", unit: "नग", mrp: 310, purchasePrice: 255, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "रिफाइंड तेल 5ली", name: "Refined Tel 5L", category: "तेल/घी", unit: "नग", mrp: 750, purchasePrice: 618, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सोयाबीन तेल 1ली", name: "Soyabean Tel 1L", category: "तेल/घी", unit: "नग", mrp: 155, purchasePrice: 128, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सोयाबीन तेल 5ली", name: "Soyabean Tel 5L", category: "तेल/घी", unit: "नग", mrp: 730, purchasePrice: 601, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सूरजमुखी तेल 1ली", name: "Surajmukhi Tel 1L", category: "तेल/घी", unit: "नग", mrp: 165, purchasePrice: 136, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सूरजमुखी तेल 5ली", name: "Surajmukhi Tel 5L", category: "तेल/घी", unit: "नग", mrp: 780, purchasePrice: 643, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मूंगफली तेल 1ली", name: "Moongphali Tel 1L", category: "तेल/घी", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "नारियल तेल 200मिली", name: "Nariyal Tel 200ml", category: "तेल/घी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "नारियल तेल 500मिली", name: "Nariyal Tel 500ml", category: "तेल/घी", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "नारियल तेल 1ली", name: "Nariyal Tel 1L", category: "तेल/घी", unit: "नग", mrp: 380, purchasePrice: 313, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "देसी घी 200मिली", name: "Desi Ghee 200ml", category: "तेल/घी", unit: "नग", mrp: 160, purchasePrice: 132, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "देसी घी 500मिली", name: "Desi Ghee 500ml", category: "तेल/घी", unit: "नग", mrp: 370, purchasePrice: 305, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "देसी घी 1किलो", name: "Desi Ghee 1kg", category: "तेल/घी", unit: "नग", mrp: 700, purchasePrice: 577, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "देसी घी 5किलो", name: "Desi Ghee 5kg", category: "तेल/घी", unit: "नग", mrp: 3300, purchasePrice: 2722, stock: 0, minStock: 1, gst: 12 },
  { hindiName: "वनस्पति घी 1किलो", name: "Vanaspati Ghee 1kg", category: "तेल/घी", unit: "नग", mrp: 220, purchasePrice: 181, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "वनस्पति घी 15किलो", name: "Vanaspati Ghee 15kg", category: "तेल/घी", unit: "नग", mrp: 3000, purchasePrice: 2474, stock: 0, minStock: 1, gst: 5 },
  { hindiName: "पाम तेल 1ली", name: "Palm Tel 1L", category: "तेल/घी", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "राइस ब्रान तेल 1ली", name: "Rice Bran Tel 1L", category: "तेल/घी", unit: "नग", mrp: 170, purchasePrice: 140, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "ऑलिव ऑयल 500मिली", name: "Olive Oil 500ml", category: "तेल/घी", unit: "नग", mrp: 450, purchasePrice: 371, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "तिल तेल 200मिली", name: "Til Tel 200ml", category: "तेल/घी", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "नमक सादा 1किलो", name: "Namak 1kg", category: "मसाले", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 0 },
  { hindiName: "नमक आयोडीन 1किलो", name: "Namak Iodine 1kg", category: "मसाले", unit: "नग", mrp: 22, purchasePrice: 17, stock: 0, minStock: 10, gst: 0 },
  { hindiName: "काला नमक 100ग्राम", name: "Kala Namak 100g", category: "मसाले", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सेंधा नमक 500ग्राम", name: "Sendha Namak 500g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "हल्दी पाउडर 100ग्राम", name: "Haldi Powder 100g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "हल्दी पाउडर 200ग्राम", name: "Haldi Powder 200g", category: "मसाले", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "हल्दी पाउडर 500ग्राम", name: "Haldi Powder 500g", category: "मसाले", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "हल्दी पाउडर 1किलो", name: "Haldi Powder 1kg", category: "मसाले", unit: "नग", mrp: 240, purchasePrice: 198, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "लाल मिर्च पाउडर 100ग्राम", name: "Lal Mirch 100g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "लाल मिर्च पाउडर 200ग्राम", name: "Lal Mirch 200g", category: "मसाले", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "लाल मिर्च पाउडर 500ग्राम", name: "Lal Mirch 500g", category: "मसाले", unit: "नग", mrp: 150, purchasePrice: 123, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "धनिया पाउडर 100ग्राम", name: "Dhaniya Powder 100g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "धनिया पाउडर 200ग्राम", name: "Dhaniya Powder 200g", category: "मसाले", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "धनिया पाउडर 500ग्राम", name: "Dhaniya Powder 500g", category: "मसाले", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "जीरा 50ग्राम", name: "Jeera 50g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "जीरा 100ग्राम", name: "Jeera 100g", category: "मसाले", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "जीरा 200ग्राम", name: "Jeera 200g", category: "मसाले", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "जीरा पाउडर 100ग्राम", name: "Jeera Powder 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "गरम मसाला 50ग्राम", name: "Garam Masala 50g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "गरम मसाला 100ग्राम", name: "Garam Masala 100g", category: "मसाले", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "गरम मसाला 200ग्राम", name: "Garam Masala 200g", category: "मसाले", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काली मिर्च 50ग्राम", name: "Kali Mirch 50g", category: "मसाले", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काली मिर्च 100ग्राम", name: "Kali Mirch 100g", category: "मसाले", unit: "नग", mrp: 85, purchasePrice: 70, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काली मिर्च पाउडर 50ग्राम", name: "Kali Mirch Powder 50g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "अजवाइन 100ग्राम", name: "Ajwain 100g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सौंफ 100ग्राम", name: "Saunf 100g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "राई 100ग्राम", name: "Rai 100g", category: "मसाले", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "मेथी दाना 100ग्राम", name: "Methi Dana 100g", category: "मसाले", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "हींग 20ग्राम", name: "Hing 20g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "हींग 50ग्राम", name: "Hing 50g", category: "मसाले", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "इमली 200ग्राम", name: "Imli 200g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "इमली 500ग्राम", name: "Imli 500g", category: "मसाले", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "अमचूर 100ग्राम", name: "Amchur 100g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सब्ज़ी मसाला 100ग्राम", name: "Sabzi Masala 100g", category: "मसाले", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सब्ज़ी मसाला 200ग्राम", name: "Sabzi Masala 200g", category: "मसाले", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "चाट मसाला 100ग्राम", name: "Chaat Masala 100g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "पाव भाजी मसाला 100ग्राम", name: "Pav Bhaji Masala 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "छोले मसाला 100ग्राम", name: "Chole Masala 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "बिरयानी मसाला 50ग्राम", name: "Biryani Masala 50g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "कड़ाई पनीर मसाला 50ग्राम", name: "Kadai Paneer Masala 50g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "राजमा मसाला 100ग्राम", name: "Rajma Masala 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "तंदूरी मसाला 100ग्राम", name: "Tandoori Masala 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सांभर मसाला 100ग्राम", name: "Sambar Masala 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "रसम पाउडर 100ग्राम", name: "Rasam Powder 100g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "करी पाउडर 100ग्राम", name: "Curry Powder 100g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "लौंग 20ग्राम", name: "Laung 20g", category: "मसाले", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "दालचीनी 50ग्राम", name: "Dalchini 50g", category: "मसाले", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "इलायची 20ग्राम", name: "Elaichi 20g", category: "मसाले", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "तेजपत्ता 20ग्राम", name: "Tejpatta 20g", category: "मसाले", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "जावित्री 20ग्राम", name: "Javitri 20g", category: "मसाले", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "कसूरी मेथी 50ग्राम", name: "Kasuri Methi 50g", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "खसखस 50ग्राम", name: "Khaskhas 50g", category: "मसाले", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "केसर 1ग्राम", name: "Kesar 1g", category: "मसाले", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "वनीला एसेंस 20मिली", name: "Vanilla Essence 20ml", category: "मसाले", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "चीनी 1किलो", name: "Cheeni 1kg", category: "चीनी/गुड़", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 10, gst: 5 },
  { hindiName: "चीनी 2किलो", name: "Cheeni 2kg", category: "चीनी/गुड़", unit: "नग", mrp: 88, purchasePrice: 72, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चीनी 5किलो", name: "Cheeni 5kg", category: "चीनी/गुड़", unit: "नग", mrp: 210, purchasePrice: 173, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चीनी 10किलो", name: "Cheeni 10kg", category: "चीनी/गुड़", unit: "नग", mrp: 410, purchasePrice: 338, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "चीनी 25किलो", name: "Cheeni 25kg", category: "चीनी/गुड़", unit: "नग", mrp: 1000, purchasePrice: 824, stock: 0, minStock: 1, gst: 5 },
  { hindiName: "शक्कर 1किलो", name: "Shakkar 1kg", category: "चीनी/गुड़", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "बूरा 500ग्राम", name: "Boora 500g", category: "चीनी/गुड़", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "गुड़ 1किलो", name: "Gud 1kg", category: "चीनी/गुड़", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "गुड़ 5किलो", name: "Gud 5kg", category: "चीनी/गुड़", unit: "नग", mrp: 280, purchasePrice: 231, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "गुड़ पाउडर 500ग्राम", name: "Gud Powder 500g", category: "चीनी/गुड़", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "खांड 500ग्राम", name: "Khand 500g", category: "चीनी/गुड़", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मिश्री 200ग्राम", name: "Mishri 200g", category: "चीनी/गुड़", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मिश्री 500ग्राम", name: "Mishri 500g", category: "चीनी/गुड़", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "खजूर गुड़ 500ग्राम", name: "Khajur Gud 500g", category: "चीनी/गुड़", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "देसी खांड 1किलो", name: "Desi Khand 1kg", category: "चीनी/गुड़", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "चाय पत्ती 100ग्राम", name: "Chai Patti 100g", category: "चाय/कॉफी", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चाय पत्ती 250ग्राम", name: "Chai Patti 250g", category: "चाय/कॉफी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चाय पत्ती 500ग्राम", name: "Chai Patti 500g", category: "चाय/कॉफी", unit: "नग", mrp: 170, purchasePrice: 140, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "चाय पत्ती 1किलो", name: "Chai Patti 1kg", category: "चाय/कॉफी", unit: "नग", mrp: 320, purchasePrice: 264, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "इलायची चाय 250ग्राम", name: "Elaichi Chai 250g", category: "चाय/कॉफी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मसाला चाय 100ग्राम", name: "Masala Chai 100g", category: "चाय/कॉफी", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "ग्रीन टी 25 बैग", name: "Green Tea 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "ग्रीन टी 50 बैग", name: "Green Tea 50 bags", category: "चाय/कॉफी", unit: "नग", mrp: 180, purchasePrice: 148, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "लेमन टी 25 बैग", name: "Lemon Tea 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "अदरक चाय 100ग्राम", name: "Adrak Chai 100g", category: "चाय/कॉफी", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "तुलसी चाय 25 बैग", name: "Tulsi Chai 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "नेस्कैफे 25ग्राम", name: "Nescafe 25g", category: "चाय/कॉफी", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "नेस्कैफे 50ग्राम", name: "Nescafe 50g", category: "चाय/कॉफी", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "नेस्कैफे 100ग्राम", name: "Nescafe 100g", category: "चाय/कॉफी", unit: "नग", mrp: 280, purchasePrice: 231, stock: 0, minStock: 2, gst: 12 },
  { hindiName: "बॉर्नविटा 200ग्राम", name: "Bournvita 200g", category: "चाय/कॉफी", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बॉर्नविटा 500ग्राम", name: "Bournvita 500g", category: "चाय/कॉफी", unit: "नग", mrp: 280, purchasePrice: 231, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बॉर्नविटा 1किलो", name: "Bournvita 1kg", category: "चाय/कॉफी", unit: "नग", mrp: 520, purchasePrice: 429, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "हॉर्लिक्स 200ग्राम", name: "Horlicks 200g", category: "चाय/कॉफी", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हॉर्लिक्स 500ग्राम", name: "Horlicks 500g", category: "चाय/कॉफी", unit: "नग", mrp: 290, purchasePrice: 239, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हॉर्लिक्स 1किलो", name: "Horlicks 1kg", category: "चाय/कॉफी", unit: "नग", mrp: 540, purchasePrice: 445, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "कॉम्प्लान 200ग्राम", name: "Complan 200g", category: "चाय/कॉफी", unit: "नग", mrp: 145, purchasePrice: 119, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पेडियाश्योर 200ग्राम", name: "Pediasure 200g", category: "चाय/कॉफी", unit: "नग", mrp: 220, purchasePrice: 181, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "कॉफी पाउडर 50ग्राम", name: "Coffee Powder 50g", category: "चाय/कॉफी", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "कॉफी पाउडर 100ग्राम", name: "Coffee Powder 100g", category: "चाय/कॉफी", unit: "नग", mrp: 110, purchasePrice: 91, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "चिकोरी कॉफी 100ग्राम", name: "Chicory Coffee 100g", category: "चाय/कॉफी", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "हर्बल टी 25 बैग", name: "Herbal Tea 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "कैमोमाइल टी 25 बैग", name: "Chamomile Tea 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "जिंजर टी 25 बैग", name: "Ginger Tea 25 bags", category: "चाय/कॉफी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "दूध पाउडर 200ग्राम", name: "Doodh Powder 200g", category: "डेयरी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "दूध पाउडर 500ग्राम", name: "Doodh Powder 500g", category: "डेयरी", unit: "नग", mrp: 220, purchasePrice: 181, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "दूध पाउडर 1किलो", name: "Doodh Powder 1kg", category: "डेयरी", unit: "नग", mrp: 420, purchasePrice: 346, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "अमूल बटर 100ग्राम", name: "Amul Butter 100g", category: "डेयरी", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "अमूल बटर 200ग्राम", name: "Amul Butter 200g", category: "डेयरी", unit: "नग", mrp: 115, purchasePrice: 95, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "अमूल बटर 500ग्राम", name: "Amul Butter 500g", category: "डेयरी", unit: "नग", mrp: 280, purchasePrice: 231, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मदर डेयरी बटर 100ग्राम", name: "Mother Dairy Butter 100g", category: "डेयरी", unit: "नग", mrp: 58, purchasePrice: 48, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "पनीर 200ग्राम", name: "Paneer 200g", category: "डेयरी", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "पनीर 500ग्राम", name: "Paneer 500g", category: "डेयरी", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "दही 200ग्राम", name: "Dahi 200g", category: "डेयरी", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "दही 400ग्राम", name: "Dahi 400g", category: "डेयरी", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "दही 1किलो", name: "Dahi 1kg", category: "डेयरी", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "श्रीखंड 200ग्राम", name: "Shrikhand 200g", category: "डेयरी", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मलाई 100ग्राम", name: "Malai 100g", category: "डेयरी", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "क्रीम 100मिली", name: "Cream 100ml", category: "डेयरी", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "छाछ 200मिली", name: "Chaach 200ml", category: "डेयरी", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "छाछ 500मिली", name: "Chaach 500ml", category: "डेयरी", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "लस्सी 200मिली", name: "Lassi 200ml", category: "डेयरी", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "लस्सी 500मिली", name: "Lassi 500ml", category: "डेयरी", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "आम लस्सी 200मिली", name: "Aam Lassi 200ml", category: "डेयरी", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "पनीर टिक्का 200ग्राम", name: "Paneer Tikka 200g", category: "डेयरी", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "चीज़ स्लाइस 200ग्राम", name: "Cheese Slice 200g", category: "डेयरी", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मोज़ेरेला चीज़ 200ग्राम", name: "Mozzarella Cheese 200g", category: "डेयरी", unit: "नग", mrp: 140, purchasePrice: 115, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मिल्क केक 200ग्राम", name: "Milk Cake 200g", category: "डेयरी", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "खोया 250ग्राम", name: "Khoya 250g", category: "डेयरी", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "कंडेंस्ड मिल्क 400ग्राम", name: "Condensed Milk 400g", category: "डेयरी", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मैगी 70ग्राम", name: "Maggi 70g", category: "पैकेज्ड फूड", unit: "नग", mrp: 14, purchasePrice: 11, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "मैगी 4पैक", name: "Maggi 4pack", category: "पैकेज्ड फूड", unit: "नग", mrp: 56, purchasePrice: 46, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मैगी मसाला", name: "Maggi Masala Noodles", category: "पैकेज्ड फूड", unit: "नग", mrp: 14, purchasePrice: 11, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "यिप्पी नूडल्स", name: "Yippee Noodles", category: "पैकेज्ड फूड", unit: "नग", mrp: 14, purchasePrice: 11, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "टॉप रामेन", name: "Top Ramen", category: "पैकेज्ड फूड", unit: "नग", mrp: 12, purchasePrice: 10, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "पार्ले-जी 100ग्राम", name: "Parle-G 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "पार्ले-जी 250ग्राम", name: "Parle-G 250g", category: "पैकेज्ड फूड", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मैरी बिस्किट", name: "Marie Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मैरी गोल्ड", name: "Marie Gold", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "गुड डे बिस्किट", name: "Good Day Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "ओरियो बिस्किट", name: "Oreo Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "50-50 बिस्किट", name: "50-50 Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "क्रीम बिस्किट", name: "Cream Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "डाइजेस्टिव बिस्किट", name: "Digestive Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बोरबॉन बिस्किट", name: "Bourbon Biscuit", category: "पैकेज्ड फूड", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "नैनकटाई", name: "Nankhatai", category: "पैकेज्ड फूड", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कुरकुरे 26ग्राम", name: "Kurkure 26g", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "कुरकुरे 70ग्राम", name: "Kurkure 70g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "लेज़ 26ग्राम", name: "Lays 26g", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "लेज़ 70ग्राम", name: "Lays 70g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बिंगो चिप्स", name: "Bingo Chips", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "अनकल चिप्स", name: "Uncle Chips", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "हल्दीराम नमकीन 200ग्राम", name: "Haldiram Namkeen 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "हल्दीराम नमकीन 400ग्राम", name: "Haldiram Namkeen 400g", category: "पैकेज्ड फूड", unit: "नग", mrp: 95, purchasePrice: 78, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "बीकानेरी नमकीन 200ग्राम", name: "Bikaneri Namkeen 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "भुजिया 200ग्राम", name: "Bhujia 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "मूंग दाल नमकीन 200ग्राम", name: "Moong Dal Namkeen 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "चिवड़ा 200ग्राम", name: "Chivda 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "चकली 200ग्राम", name: "Chakli 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "पापड़ 200ग्राम", name: "Papad 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "उड़द पापड़ 200ग्राम", name: "Urad Papad 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "आचार आम 200ग्राम", name: "Achar Aam 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "आचार आम 400ग्राम", name: "Achar Aam 400g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "आचार नींबू 200ग्राम", name: "Achar Nimbu 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "आचार मिक्स 400ग्राम", name: "Achar Mix 400g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मुरब्बा आंवला 500ग्राम", name: "Murabba Amla 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "सत्तू 500ग्राम", name: "Sattu 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "मखाना 100ग्राम", name: "Makhana 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "ड्राई फ्रूट मिक्स 100ग्राम", name: "Dry Fruit Mix 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "किशमिश 100ग्राम", name: "Kishmish 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "काजू 100ग्राम", name: "Kaju 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "बादाम 100ग्राम", name: "Badam 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "पिस्ता 50ग्राम", name: "Pista 50g", category: "पैकेज्ड फूड", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "अखरोट 100ग्राम", name: "Akhrot 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "खजूर 250ग्राम", name: "Khajur 250g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "अंजीर 100ग्राम", name: "Anjir 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "रस्क 200ग्राम", name: "Rusk 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "रस्क 400ग्राम", name: "Rusk 400g", category: "पैकेज्ड फूड", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "ब्रेड सफेद", name: "Bread White", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "ब्रेड ब्राउन", name: "Bread Brown", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "पाव 4पीस", name: "Pav 4pcs", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "बिस्किट टिन", name: "Biscuit Tin", category: "पैकेज्ड फूड", unit: "नग", mrp: 180, purchasePrice: 148, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "क्रैकर्स 100ग्राम", name: "Crackers 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कॉर्न फ्लेक्स 250ग्राम", name: "Corn Flakes 250g", category: "पैकेज्ड फूड", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ओट्स 500ग्राम", name: "Oats 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "म्यूसली 500ग्राम", name: "Muesli 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पोर्रिज 500ग्राम", name: "Porridge 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "चॉकलेट सॉस 200ग्राम", name: "Chocolate Sauce 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "जैम 500ग्राम", name: "Jam 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "जेली 200ग्राम", name: "Jelly 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "पीनट बटर 200ग्राम", name: "Peanut Butter 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हनी 250ग्राम", name: "Honey 250g", category: "पैकेज्ड फूड", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हनी 500ग्राम", name: "Honey 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 240, purchasePrice: 198, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "च्यवनप्राश 500ग्राम", name: "Chyawanprash 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 180, purchasePrice: 148, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "च्यवनप्राश 1किलो", name: "Chyawanprash 1kg", category: "पैकेज्ड फूड", unit: "नग", mrp: 320, purchasePrice: 264, stock: 0, minStock: 2, gst: 12 },
  { hindiName: "टोमैटो केचप 500ग्राम", name: "Tomato Ketchup 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "चिली सॉस 200ग्राम", name: "Chilli Sauce 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "सोया सॉस 200मिली", name: "Soya Sauce 200ml", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "विनेगर 500मिली", name: "Vinegar 500ml", category: "पैकेज्ड फूड", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "मेयोनेज़ 200ग्राम", name: "Mayonnaise 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "मस्टर्ड सॉस 200ग्राम", name: "Mustard Sauce 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "नूडल्स राइस 200ग्राम", name: "Noodles Rice 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पास्ता 500ग्राम", name: "Pasta 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "मैकरोनी 500ग्राम", name: "Macaroni 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "स्पेगेटी 500ग्राम", name: "Spaghetti 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "इडली मिक्स 500ग्राम", name: "Idli Mix 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "डोसा मिक्स 500ग्राम", name: "Dosa Mix 500g", category: "पैकेज्ड फूड", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "उपमा मिक्स 200ग्राम", name: "Upma Mix 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "ढोकला मिक्स 200ग्राम", name: "Dhokla Mix 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "गुलाब जामुन मिक्स 200ग्राम", name: "Gulab Jamun Mix 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "जलेबी मिक्स 200ग्राम", name: "Jalebi Mix 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हलवा मिक्स 200ग्राम", name: "Halwa Mix 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बेकिंग सोडा 100ग्राम", name: "Baking Soda 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बेकिंग पाउडर 100ग्राम", name: "Baking Powder 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "ईनो फ्रूट साल्ट", name: "Eno Fruit Salt", category: "पैकेज्ड फूड", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "कस्टर्ड पाउडर 100ग्राम", name: "Custard Powder 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कोको पाउडर 100ग्राम", name: "Coco Powder 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "कॉर्नफ्लोर 200ग्राम", name: "Cornflour 200g", category: "पैकेज्ड फूड", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "अरारोट 100ग्राम", name: "Araroot 100g", category: "पैकेज्ड फूड", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सर्फ एक्सेल 500ग्राम", name: "Surf Excel 500g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सर्फ एक्सेल 1किलो", name: "Surf Excel 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 190, purchasePrice: 157, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सर्फ एक्सेल 2किलो", name: "Surf Excel 2kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 360, purchasePrice: 297, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "एरियल 500ग्राम", name: "Ariel 500g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "एरियल 1किलो", name: "Ariel 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 190, purchasePrice: 157, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "टाइड 500ग्राम", name: "Tide 500g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 85, purchasePrice: 70, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "टाइड 1किलो", name: "Tide 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 160, purchasePrice: 132, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "व्हील 1किलो", name: "Wheel 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "व्हील 2किलो", name: "Wheel 2kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 115, purchasePrice: 95, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "निरमा 1किलो", name: "Nirma 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "निरमा 2किलो", name: "Nirma 2kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 105, purchasePrice: 86, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "रिन 500ग्राम", name: "Rin 500g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रिन 1किलो", name: "Rin 1kg", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 115, purchasePrice: 95, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सुपर रिन बार", name: "Super Rin Bar", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "विम बार 200ग्राम", name: "Vim Bar 200g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "विम बार 400ग्राम", name: "Vim Bar 400g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "विम लिक्विड 250मिली", name: "Vim Liquid 250ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "विम लिक्विड 500मिली", name: "Vim Liquid 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "विम लिक्विड 1ली", name: "Vim Liquid 1L", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 165, purchasePrice: 136, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पॉट क्लीनर 500ग्राम", name: "Pot Cleaner 500g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "लाइफबॉय साबुन 100ग्राम", name: "Lifebuoy Soap 100g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "लाइफबॉय साबुन 150ग्राम", name: "Lifebuoy Soap 150g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "लक्स साबुन 100ग्राम", name: "Lux Soap 100g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "लक्स साबुन 150ग्राम", name: "Lux Soap 150g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "डेटॉल साबुन 100ग्राम", name: "Dettol Soap 100g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "डेटॉल साबुन 75ग्राम", name: "Dettol Soap 75g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सेवलॉन साबुन", name: "Savlon Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हमाम साबुन", name: "Hamam Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "मैसूर सैंडल साबुन", name: "Mysore Sandal Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पियर्स साबुन", name: "Pears Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "डव साबुन 100ग्राम", name: "Dove Soap 100g", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पतंजलि साबुन", name: "Patanjali Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मेडिमिक्स साबुन", name: "Medimix Soap", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हार्पिक 500मिली", name: "Harpic 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हार्पिक 1ली", name: "Harpic 1L", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 160, purchasePrice: 132, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डोमेक्स 500मिली", name: "Domex 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 85, purchasePrice: 70, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "कॉलिन 200मिली", name: "Colin 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "कॉलिन 500मिली", name: "Colin 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फिनाइल 500मिली", name: "Phenyl 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फिनाइल 1ली", name: "Phenyl 1L", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फ्लोर क्लीनर 1ली", name: "Floor Cleaner 1L", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "टॉयलेट क्लीनर 500मिली", name: "Toilet Cleaner 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बाथरूम क्लीनर 500मिली", name: "Bathroom Cleaner 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "किचन क्लीनर 500मिली", name: "Kitchen Cleaner 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ग्लास क्लीनर 500मिली", name: "Glass Cleaner 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 75, purchasePrice: 62, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "मल्टी सर्फेस क्लीनर", name: "Multi Surface Cleaner", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "एयर फ्रेशनर 200मिली", name: "Air Freshener 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "मच्छर अगरबत्ती", name: "Machar Agarbatti", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "गुड नाइट मैट", name: "Good Night Mat", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "गुड नाइट लिक्विड", name: "Good Night Liquid", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ऑल आउट मशीन", name: "All Out Machine", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ऑल आउट रिफिल", name: "All Out Refill", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "मॉर्टीन स्प्रे", name: "Mortein Spray", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हिट स्प्रे", name: "Hit Spray", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बायगॉन स्प्रे", name: "Baygon Spray", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 140, purchasePrice: 115, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "लाइज़ोल 500मिली", name: "Lysol 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 160, purchasePrice: 132, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डेटॉल लिक्विड 200मिली", name: "Dettol Liquid 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डेटॉल लिक्विड 500मिली", name: "Dettol Liquid 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 180, purchasePrice: 148, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सेवलॉन लिक्विड 200मिली", name: "Savlon Liquid 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 75, purchasePrice: 62, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सैनिटाइज़र 200मिली", name: "Sanitizer 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हैंड वॉश 200मिली", name: "Handwash 200ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हैंड वॉश 500मिली", name: "Handwash 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डिशवॉश लिक्विड 500मिली", name: "Dishwash Liquid 500ml", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "स्क्रबर", name: "Scrubber", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "स्पंज", name: "Sponge", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "झाड़ू", name: "Jhadu", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पोछा", name: "Pocha", category: "साबुन/डिटर्जेंट", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "कोलगेट 100ग्राम", name: "Colgate 100g", category: "पर्सनल केयर", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कोलगेट 200ग्राम", name: "Colgate 200g", category: "पर्सनल केयर", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कोलगेट स्ट्रॉन्ग टीथ", name: "Colgate Strong Teeth", category: "पर्सनल केयर", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पतंजलि दंत क्रीम 100ग्राम", name: "Patanjali Dant Cream 100g", category: "पर्सनल केयर", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पतंजलि दंत क्रीम 200ग्राम", name: "Patanjali Dant Cream 200g", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "क्लोज़ अप 100ग्राम", name: "Close Up 100g", category: "पर्सनल केयर", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पेप्सोडेंट 100ग्राम", name: "Pepsodent 100g", category: "पर्सनल केयर", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सेंसोडाइन 70ग्राम", name: "Sensodyne 70g", category: "पर्सनल केयर", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ओरल-बी टूथब्रश", name: "Oral-B Toothbrush", category: "पर्सनल केयर", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कोलगेट टूथब्रश", name: "Colgate Toothbrush", category: "पर्सनल केयर", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बच्चों का टूथब्रश", name: "Bachcho Ka Toothbrush", category: "पर्सनल केयर", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "टंग क्लीनर", name: "Tongue Cleaner", category: "पर्सनल केयर", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "माउथवॉश 250मिली", name: "Mouthwash 250ml", category: "पर्सनल केयर", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डेंटल फ्लॉस", name: "Dental Floss", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पैंटीन शैम्पू 75मिली", name: "Pantene Shampoo 75ml", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पैंटीन शैम्पू 180मिली", name: "Pantene Shampoo 180ml", category: "पर्सनल केयर", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हेड एंड शोल्डर्स 72मिली", name: "Head Shoulders 72ml", category: "पर्सनल केयर", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेड एंड शोल्डर्स 180मिली", name: "Head Shoulders 180ml", category: "पर्सनल केयर", unit: "नग", mrp: 140, purchasePrice: 115, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डव शैम्पू 80मिली", name: "Dove Shampoo 80ml", category: "पर्सनल केयर", unit: "नग", mrp: 65, purchasePrice: 53, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सनसिल्क शैम्पू 80मिली", name: "Sunsilk Shampoo 80ml", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सनसिल्क शैम्पू 180मिली", name: "Sunsilk Shampoo 180ml", category: "पर्सनल केयर", unit: "नग", mrp: 115, purchasePrice: 95, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पतंजलि केश कांति", name: "Patanjali Kesh Kanti", category: "पर्सनल केयर", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "क्लिनिक प्लस शैम्पू", name: "Clinic Plus Shampoo", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेयर कंडीशनर 175मिली", name: "Hair Conditioner 175ml", category: "पर्सनल केयर", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "नारियल तेल 100मिली", name: "Nariyal Tel 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "नारियल तेल 200मिली", name: "Nariyal Tel 200ml", category: "पर्सनल केयर", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "नारियल तेल 500मिली", name: "Nariyal Tel 500ml", category: "पर्सनल केयर", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पैराशूट तेल 75मिली", name: "Parachute Tel 75ml", category: "पर्सनल केयर", unit: "नग", mrp: 45, purchasePrice: 37, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पैराशूट तेल 200मिली", name: "Parachute Tel 200ml", category: "पर्सनल केयर", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "आंवला तेल 200मिली", name: "Amla Tel 200ml", category: "पर्सनल केयर", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बादाम तेल 100मिली", name: "Badam Tel 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "हेयर जेल 100ग्राम", name: "Hair Gel 100g", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेयर क्रीम 100ग्राम", name: "Hair Cream 100g", category: "पर्सनल केयर", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेयर सीरम 100मिली", name: "Hair Serum 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "मेहंदी पाउडर 50ग्राम", name: "Mehandi Powder 50g", category: "पर्सनल केयर", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "वैसलीन 50मिली", name: "Vaseline 50ml", category: "पर्सनल केयर", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "वैसलीन 100मिली", name: "Vaseline 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "वैसलीन 250मिली", name: "Vaseline 250ml", category: "पर्सनल केयर", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "निवेया क्रीम 50मिली", name: "Nivea Cream 50ml", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "निवेया क्रीम 100मिली", name: "Nivea Cream 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 140, purchasePrice: 115, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "लोशन 200मिली", name: "Lotion 200ml", category: "पर्सनल केयर", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फेस वॉश 100मिली", name: "Face Wash 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फेस क्रीम 50ग्राम", name: "Face Cream 50g", category: "पर्सनल केयर", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सनस्क्रीन SPF30 50मिली", name: "Sunscreen SPF30 50ml", category: "पर्सनल केयर", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "टेलकम पाउडर 100ग्राम", name: "Talcum Powder 100g", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "टेलकम पाउडर 200ग्राम", name: "Talcum Powder 200g", category: "पर्सनल केयर", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डियोडरेंट 150मिली", name: "Deodorant 150ml", category: "पर्सनल केयर", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "परफ्यूम", name: "Perfume", category: "पर्सनल केयर", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सेनेटरी पैड", name: "Sanitary Pad", category: "पर्सनल केयर", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "सेनेटरी पैड रात", name: "Sanitary Pad Night", category: "पर्सनल केयर", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "टैम्पॉन", name: "Tampon", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 0 },
  { hindiName: "पैंटी लाइनर", name: "Panty Liner", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 0 },
  { hindiName: "शेविंग क्रीम 70ग्राम", name: "Shaving Cream 70g", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "शेविंग जेल 200मिली", name: "Shaving Gel 200ml", category: "पर्सनल केयर", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "रेज़र", name: "Razor", category: "पर्सनल केयर", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रेज़र 4पीस", name: "Razor 4pcs", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "आफ्टरशेव 100मिली", name: "Aftershave 100ml", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ट्रिमर", name: "Trimmer", category: "पर्सनल केयर", unit: "नग", mrp: 500, purchasePrice: 413, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "नेल कटर", name: "Nail Cutter", category: "पर्सनल केयर", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "रूई 50ग्राम", name: "Rui 50g", category: "पर्सनल केयर", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "ईयर बड्स", name: "Ear Buds", category: "पर्सनल केयर", unit: "नग", mrp: 35, purchasePrice: 28, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बैंडेड 10पीस", name: "Band-Aid 10pcs", category: "पर्सनल केयर", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "एंटीसेप्टिक क्रीम", name: "Antiseptic Cream", category: "पर्सनल केयर", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "बर्न क्रीम", name: "Burn Cream", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "कंघी", name: "Kanghi", category: "पर्सनल केयर", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेयर बैंड", name: "Hair Band", category: "पर्सनल केयर", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हेयर पिन", name: "Hair Pin", category: "पर्सनल केयर", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "काजल", name: "Kajal", category: "पर्सनल केयर", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "लिपस्टिक", name: "Lipstick", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "नेल पॉलिश", name: "Nail Polish", category: "पर्सनल केयर", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "नेल रिमूवर", name: "Nail Remover", category: "पर्सनल केयर", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "मेकअप रिमूवर", name: "Makeup Remover", category: "पर्सनल केयर", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सेफ्टी पिन", name: "Safety Pin", category: "पर्सनल केयर", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "सिलाई धागा", name: "Silai Dhaga", category: "पर्सनल केयर", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "बटन", name: "Button", category: "पर्सनल केयर", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "पानी 250मिली", name: "Pani 250ml", category: "पेय", unit: "नग", mrp: 10, purchasePrice: 7, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पानी 500मिली", name: "Pani 500ml", category: "पेय", unit: "नग", mrp: 10, purchasePrice: 7, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पानी 1ली", name: "Pani 1L", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 14, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पानी 2ली", name: "Pani 2L", category: "पेय", unit: "नग", mrp: 35, purchasePrice: 24, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "थम्स अप 200मिली", name: "Thums Up 200ml", category: "पेय", unit: "नग", mrp: 15, purchasePrice: 11, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "थम्स अप 300मिली", name: "Thums Up 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "थम्स अप 600मिली", name: "Thums Up 600ml", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 30, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "थम्स अप 1.25ली", name: "Thums Up 1.25L", category: "पेय", unit: "नग", mrp: 65, purchasePrice: 49, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "थम्स अप 2ली", name: "Thums Up 2L", category: "पेय", unit: "नग", mrp: 100, purchasePrice: 74, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "कोका कोला 300मिली", name: "Coca Cola 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "कोका कोला 600मिली", name: "Coca Cola 600ml", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 30, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "कोका कोला 2ली", name: "Coca Cola 2L", category: "पेय", unit: "नग", mrp: 100, purchasePrice: 74, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "स्प्राइट 300मिली", name: "Sprite 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "स्प्राइट 600मिली", name: "Sprite 600ml", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 30, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "स्प्राइट 2ली", name: "Sprite 2L", category: "पेय", unit: "नग", mrp: 100, purchasePrice: 74, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "लिम्का 300मिली", name: "Limca 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "फैंटा 300मिली", name: "Fanta 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "माज़ा 200मिली", name: "Maaza 200ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 14, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "माज़ा 600मिली", name: "Maaza 600ml", category: "पेय", unit: "नग", mrp: 55, purchasePrice: 41, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "माज़ा 1.2ली", name: "Maaza 1.2L", category: "पेय", unit: "नग", mrp: 90, purchasePrice: 67, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "फ्रूटी 125मिली", name: "Frooti 125ml", category: "पेय", unit: "नग", mrp: 10, purchasePrice: 7, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "फ्रूटी 200मिली", name: "Frooti 200ml", category: "पेय", unit: "नग", mrp: 15, purchasePrice: 11, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "फ्रूटी 500मिली", name: "Frooti 500ml", category: "पेय", unit: "नग", mrp: 35, purchasePrice: 26, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "स्लाइस 200मिली", name: "Slice 200ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "रियल जूस 200मिली", name: "Real Juice 200ml", category: "पेय", unit: "नग", mrp: 30, purchasePrice: 22, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रियल जूस 1ली", name: "Real Juice 1L", category: "पेय", unit: "नग", mrp: 120, purchasePrice: 88, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "ट्रोपिकाना 200मिली", name: "Tropicana 200ml", category: "पेय", unit: "नग", mrp: 35, purchasePrice: 26, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "ट्रोपिकाना 1ली", name: "Tropicana 1L", category: "पेय", unit: "नग", mrp: 130, purchasePrice: 96, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पेप्सी 300मिली", name: "Pepsi 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "पेप्सी 600मिली", name: "Pepsi 600ml", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 30, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "माउंटेन ड्यू 300मिली", name: "Mountain Dew 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "7अप 300मिली", name: "7Up 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "मिरिंडा 300मिली", name: "Miranda 300ml", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "रेड बुल 250मिली", name: "Red Bull 250ml", category: "पेय", unit: "नग", mrp: 120, purchasePrice: 88, stock: 0, minStock: 3, gst: 28 },
  { hindiName: "रिचाज 250मिली", name: "Recharge 250ml", category: "पेय", unit: "नग", mrp: 30, purchasePrice: 22, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "ग्लूकोज D 500ग्राम", name: "Glucose D 500g", category: "पेय", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "इलेक्ट्रल पाउडर", name: "Electral Powder", category: "पेय", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "ओआरएस पाउडर", name: "ORS Powder", category: "पेय", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "जल जीरा 500मिली", name: "Jal Jeera 500ml", category: "पेय", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "आम पन्ना", name: "Aam Panna", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "इमली का शर्बत", name: "Imli Sharbat", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "गुलाब शर्बत 500मिली", name: "Gulab Sharbat 500ml", category: "पेय", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "रूह अफज़ा 750मिली", name: "Rooh Afza 750ml", category: "पेय", unit: "नग", mrp: 220, purchasePrice: 181, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "नींबू पानी", name: "Nimbu Pani", category: "पेय", unit: "नग", mrp: 20, purchasePrice: 15, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "सोडा 300मिली", name: "Soda 300ml", category: "पेय", unit: "नग", mrp: 15, purchasePrice: 11, stock: 0, minStock: 10, gst: 28 },
  { hindiName: "टोनिक वाटर", name: "Tonic Water", category: "पेय", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "कोकोनट वाटर 200मिली", name: "Coconut Water 200ml", category: "पेय", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "दूध 500मिली", name: "Doodh 500ml", category: "पेय", unit: "नग", mrp: 28, purchasePrice: 22, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "दूध 1ली", name: "Doodh 1L", category: "पेय", unit: "नग", mrp: 55, purchasePrice: 45, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "सोया मिल्क 200मिली", name: "Soya Milk 200ml", category: "पेय", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 5 },
  { hindiName: "बादाम मिल्क 200मिली", name: "Badam Milk 200ml", category: "पेय", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "डेयरी मिल्क 13ग्राम", name: "Dairy Milk 13g", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "डेयरी मिल्क 36ग्राम", name: "Dairy Milk 36g", category: "स्नैक्स", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "किटकैट", name: "KitKat", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "5 स्टार", name: "5 Star", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "बाउंटी", name: "Bounty", category: "स्नैक्स", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मिल्कीबार", name: "Milkybar", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पर्क", name: "Perk", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मंच", name: "Munch", category: "स्नैक्स", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "क्लच", name: "Clutch", category: "स्नैक्स", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "मैंगो बाइट टॉफी", name: "Mango Bite Toffee", category: "स्नैक्स", unit: "नग", mrp: 1, purchasePrice: 0.7, stock: 0, minStock: 50, gst: 18 },
  { hindiName: "एक्लेयर्स टॉफी", name: "Eclairs Toffee", category: "स्नैक्स", unit: "नग", mrp: 1, purchasePrice: 0.7, stock: 0, minStock: 50, gst: 18 },
  { hindiName: "कॉफी बाइट", name: "Coffee Bite", category: "स्नैक्स", unit: "नग", mrp: 1, purchasePrice: 0.7, stock: 0, minStock: 50, gst: 18 },
  { hindiName: "हॉपकॉर्न", name: "Popcorn", category: "स्नैक्स", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "चॉकलेट पाई 6पीस", name: "Chocolate Pie 6pcs", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कुकीज़ 150ग्राम", name: "Cookies 150g", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "वेफर 30ग्राम", name: "Wafer 30g", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "चिप्स मिक्स 30ग्राम", name: "Chips Mix 30g", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पफ्स 30ग्राम", name: "Puffs 30g", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "रोस्टेड मूंगफली 100ग्राम", name: "Roasted Moongphali 100g", category: "स्नैक्स", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रोस्टेड चना 100ग्राम", name: "Roasted Chana 100g", category: "स्नैक्स", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बाकरवड़ी 200ग्राम", name: "Bakarwadi 200g", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "लड्डू 250ग्राम", name: "Laddu 250g", category: "स्नैक्स", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "बर्फी 250ग्राम", name: "Barfi 250g", category: "स्नैक्स", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "गुलाब जामुन टिन", name: "Gulab Jamun Tin", category: "स्नैक्स", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "रसगुल्ला टिन", name: "Rasgulla Tin", category: "स्नैक्स", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "जलेबी 250ग्राम", name: "Jalebi 250g", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सेव 200ग्राम", name: "Sev 200g", category: "स्नैक्स", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "गट्टा 200ग्राम", name: "Gatta 200g", category: "स्नैक्स", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "नान खटाई 200ग्राम", name: "Nan Khatai 200g", category: "स्नैक्स", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "बिस्किट असोर्टेड", name: "Biscuit Assorted", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "चॉकलेट बार मिक्स", name: "Chocolate Bar Mix", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "जेली बीन्स", name: "Jelly Beans", category: "स्नैक्स", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "गम", name: "Chewing Gum", category: "स्नैक्स", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "बब्बल गम", name: "Bubble Gum", category: "स्नैक्स", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "पॉप टेट्स", name: "Pop Tarts", category: "स्नैक्स", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "प्रोटीन बार", name: "Protein Bar", category: "स्नैक्स", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "एनर्जी बार", name: "Energy Bar", category: "स्नैक्स", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ग्रेनोला बार", name: "Granola Bar", category: "स्नैक्स", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "राइस केक", name: "Rice Cake", category: "स्नैक्स", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "कॉर्न पफ", name: "Corn Puff", category: "स्नैक्स", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "माचिस", name: "Matchbox", category: "अन्य", unit: "नग", mrp: 2, purchasePrice: 1.5, stock: 0, minStock: 20, gst: 18 },
  { hindiName: "माचिस 10पैक", name: "Matchbox 10pack", category: "अन्य", unit: "नग", mrp: 18, purchasePrice: 14, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "अगरबत्ती 20स्टिक", name: "Agarbatti 20stick", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "अगरबत्ती 100स्टिक", name: "Agarbatti 100stick", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "धूपबत्ती", name: "Dhupbatti", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "कपूर", name: "Kapur", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "मोमबत्ती", name: "Mombatti", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "मोमबत्ती 6पैक", name: "Mombatti 6pack", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "दीपक बाती", name: "Deepak Bati", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "हवन सामग्री", name: "Havan Samagri", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "पूजा थाली", name: "Puja Thali", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "सिंदूर", name: "Sindur", category: "अन्य", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "रोली", name: "Roli", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "कुमकुम", name: "Kumkum", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "अबीर गुलाल", name: "Abir Gulal", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 0 },
  { hindiName: "पॉलीथीन बैग छोटा", name: "Polythene Bag Chota", category: "अन्य", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पॉलीथीन बैग बड़ा", name: "Polythene Bag Bada", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "पेपर बैग", name: "Paper Bag", category: "अन्य", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 10, gst: 18 },
  { hindiName: "बटुआ बैग", name: "Batua Bag", category: "अन्य", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रस्सी 10मीटर", name: "Rassi 10m", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सेलो टेप", name: "Cello Tape", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "रबर बैंड", name: "Rubber Band", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "पिन", name: "Pin", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "क्लिप", name: "Clip", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "फेविकोल", name: "Fevicol", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "म-सील", name: "M-Seal", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "सेल बैटरी AA 2पैक", name: "Battery AA 2pack", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 22, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "सेल बैटरी AAA 2पैक", name: "Battery AAA 2pack", category: "अन्य", unit: "नग", mrp: 25, purchasePrice: 19, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "सेल बैटरी D", name: "Battery D", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 28 },
  { hindiName: "सेल बैटरी 9V", name: "Battery 9V", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 28 },
  { hindiName: "बल्ब LED 5W", name: "LED Bulb 5W", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बल्ब LED 9W", name: "LED Bulb 9W", category: "अन्य", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बल्ब LED 12W", name: "LED Bulb 12W", category: "अन्य", unit: "नग", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "ट्यूब लाइट", name: "Tube Light", category: "अन्य", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "एक्सटेंशन कॉर्ड", name: "Extension Cord", category: "अन्य", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "स्विच बोर्ड", name: "Switch Board", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "टेप वायर", name: "Tape Wire", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बाल्टी 10ली", name: "Balti 10L", category: "अन्य", unit: "नग", mrp: 120, purchasePrice: 99, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "बाल्टी 15ली", name: "Balti 15L", category: "अन्य", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "मग", name: "Mug", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "तसला", name: "Tasla", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "लोटा", name: "Lota", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "जग 1ली", name: "Jag 1L", category: "अन्य", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "थाली", name: "Thali", category: "अन्य", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "कटोरा", name: "Katora", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "गिलास", name: "Glass", category: "अन्य", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "चम्मच सेट", name: "Chammach Set", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "प्लेट", name: "Plate", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डिस्पोजल कप 50पीस", name: "Disposal Cup 50pcs", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डिस्पोजल प्लेट 50पीस", name: "Disposal Plate 50pcs", category: "अन्य", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "डिस्पोजल चम्मच 50पीस", name: "Disposal Spoon 50pcs", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "एल्युमिनियम फॉयल", name: "Aluminium Foil", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "क्लिंग रैप", name: "Cling Wrap", category: "अन्य", unit: "नग", mrp: 70, purchasePrice: 57, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "बटर पेपर", name: "Butter Paper", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "किचन टिशू", name: "Kitchen Tissue", category: "अन्य", unit: "नग", mrp: 60, purchasePrice: 49, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "फेस टिशू", name: "Face Tissue", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "टॉयलेट पेपर 3रोल", name: "Toilet Paper 3roll", category: "अन्य", unit: "नग", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "नैपकिन", name: "Napkin", category: "अन्य", unit: "नग", mrp: 40, purchasePrice: 33, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "पेंसिल", name: "Pencil", category: "अन्य", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "पेन", name: "Pen", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 10, gst: 12 },
  { hindiName: "कॉपी नोटबुक", name: "Copy Notebook", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "स्केल", name: "Scale", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "इरेज़र", name: "Eraser", category: "अन्य", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "चाक", name: "Chalk", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "ग्लू स्टिक", name: "Glue Stick", category: "अन्य", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "स्टेपलर", name: "Stapler", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "स्टेपल पिन", name: "Staple Pin", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "नुस्खा पैड", name: "Nuskha Pad", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "बिल बुक", name: "Bill Book", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "मच्छरदानी", name: "Machardani", category: "अन्य", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 2, gst: 12 },
  { hindiName: "चटाई", name: "Chatai", category: "अन्य", unit: "नग", mrp: 150, purchasePrice: 124, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "तकिया", name: "Takiya", category: "अन्य", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "कंबल", name: "Kambal", category: "अन्य", unit: "नग", mrp: 400, purchasePrice: 330, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "चादर", name: "Chader", category: "अन्य", unit: "नग", mrp: 200, purchasePrice: 165, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "तौलिया", name: "Towliya", category: "अन्य", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "हैंगर", name: "Hanger", category: "अन्य", unit: "नग", mrp: 10, purchasePrice: 8, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "बटन हुक", name: "Button Hook", category: "अन्य", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "ताला", name: "Tala", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "चाबी", name: "Chabi", category: "अन्य", unit: "नग", mrp: 20, purchasePrice: 16, stock: 0, minStock: 5, gst: 18 },
  { hindiName: "हथौड़ा", name: "Hathauda", category: "अन्य", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "पेचकस", name: "Pechkas", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "प्लास", name: "Plas", category: "अन्य", unit: "नग", mrp: 80, purchasePrice: 66, stock: 0, minStock: 2, gst: 18 },
  { hindiName: "कैंची", name: "Kainchi", category: "अन्य", unit: "नग", mrp: 50, purchasePrice: 41, stock: 0, minStock: 3, gst: 18 },
  { hindiName: "थर्मामीटर", name: "Thermometer", category: "अन्य", unit: "नग", mrp: 100, purchasePrice: 82, stock: 0, minStock: 2, gst: 12 },
  { hindiName: "बीपी मशीन", name: "BP Machine", category: "अन्य", unit: "नग", mrp: 800, purchasePrice: 660, stock: 0, minStock: 1, gst: 12 },
  { hindiName: "ग्लूकोमीटर", name: "Glucometer", category: "अन्य", unit: "नग", mrp: 600, purchasePrice: 495, stock: 0, minStock: 1, gst: 12 },
  { hindiName: "ग्लूकोमीटर स्ट्रिप", name: "Glucometer Strip", category: "अन्य", unit: "नग", mrp: 300, purchasePrice: 247, stock: 0, minStock: 3, gst: 12 },
  { hindiName: "ओआरएस सैचेट", name: "ORS Sachet", category: "अन्य", unit: "नग", mrp: 5, purchasePrice: 4, stock: 0, minStock: 10, gst: 12 },
  { hindiName: "पैरासिटामोल 10 टैब", name: "Paracetamol 10tab", category: "अन्य", unit: "नग", mrp: 15, purchasePrice: 12, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "एंटासिड टैब", name: "Antacid Tab", category: "अन्य", unit: "नग", mrp: 25, purchasePrice: 20, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "विटामिन C टैब", name: "Vitamin C Tab", category: "अन्य", unit: "नग", mrp: 30, purchasePrice: 24, stock: 0, minStock: 5, gst: 12 },
  { hindiName: "सरसों", name: "Sarson", category: "अन्य", unit: "किलो", mrp: 80, purchasePrice: 66, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "तिल", name: "Til", category: "अन्य", unit: "किलो", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "अलसी", name: "Alsi", category: "अन्य", unit: "किलो", mrp: 90, purchasePrice: 74, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "कद्दू के बीज", name: "Kaddu Beej", category: "अन्य", unit: "किलो", mrp: 150, purchasePrice: 124, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "सूरजमुखी बीज", name: "Surajmukhi Beej", category: "अन्य", unit: "किलो", mrp: 130, purchasePrice: 107, stock: 0, minStock: 3, gst: 5 },
  { hindiName: "चिया सीड", name: "Chia Seed", category: "अन्य", unit: "किलो", mrp: 250, purchasePrice: 206, stock: 0, minStock: 2, gst: 5 },
  { hindiName: "फ्लैक्स सीड", name: "Flax Seed", category: "अन्य", unit: "किलो", mrp: 120, purchasePrice: 99, stock: 0, minStock: 3, gst: 5 },
];

export async function seedItemsForUser(userId) {
  const toInsert = SEED_ITEMS.map((item) => ({
    userId,
    name: item.name,
    hindiName: item.hindiName,
    category: item.category,
    brand: null,
    unit: item.unit,
    mrp: item.mrp,
    purchasePrice: item.purchasePrice,
    stock: 0,
    minStock: item.minStock,
    barcode: null,
    gst: item.gst,
    hsn: null,
    expiry: null,
    active: 1,
  }));

  await db.insert(items).values(toInsert);
}